# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Pratibha Dutta
tagline:             'Human Resource Professional'
description:         ''
url:                 http://pratibhadutta.us
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Ishan Kapoor
  url:               
  email:             

# Custom vars
version:             1.0.0
